name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        id: install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: "github-action[bot]"
          user_email: "github-action[bot]@noreply@github.com"
